  Develop[m
  api/autenticacao-required[m
  api/django-ninja-webpage-get-all-endpoint[m
  api/newslleter[m
  feature/add-api-adopt-google[m
  feature/admin-customizado[m
  feature/adminlte[m
  feature/adminlte-customizado[m
  feature/base-template[m
  feature/base-template-404[m
  feature/booking-form-validation-backend[m
  feature/booking-form-validation-frontend[m
  feature/cache[m
  feature/contato-form-validacao-front[m
  feature/contato-form-validacao-simples-backend[m
  feature/django-admin-basic[m
  feature/export-csv-django-admin[m
  feature/form-contato[m
  feature/landing-page-fixture[m
  feature/logging-try-except[m
  feature/model-webpage[m
  feature/newsletter[m
  feature/privacidade-no-rodape[m
  feature/readme-com-debug[m
  feature/readme-update-colorfield-lib[m
  feature/readme-update-load-fixures[m
  feature/statics[m
  feature/translate[m
  feature/unfold-admin[m
  feature/user-terms-no-rodape[m
  feature/utils[m
  feature/view-queryset-context[m
* [32mmain[m
  refact/model-landing-page[m
  release/v1.0.0-alpha[m
  release/v1.0.1-alpha[m
  release/v2.0.0-beta[m
  release/v2.1.0-beta[m
  v2.1.0-beta[m
