# Generated by Django 4.2.16 on 2024-09-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservadmin', '0002_clientes_alter_colaboradores_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone_celular',
            field=models.CharField(max_length=22, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=22, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='telefone_celular',
            field=models.CharField(max_length=22, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=22, verbose_name='Telefone Fixo'),
        ),
    ]
