# Generated by Django 4.2.16 on 2024-09-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservadmin', '0003_clientes_created_at_clientes_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
