# Generated by Django 4.2.15 on 2024-09-10 02:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarServ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Logo da Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da Empresa')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone da Empresa')),
                ('working_hours_weekdays', models.CharField(max_length=255, verbose_name='Horário de Funcionamento (Segunda a Sexta)')),
                ('working_hours_saturday', models.CharField(max_length=255, verbose_name='Horário de Funcionamento (Sábado)')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('terms_of_service', models.URLField(blank=True, null=True, verbose_name='Termos de Serviço')),
                ('privacy_policy', models.URLField(blank=True, null=True, verbose_name='Política de Privacidade')),
                ('show_navbar', models.BooleanField(default=True, verbose_name='Exibir Barra de Navegação')),
                ('show_carousel', models.BooleanField(default=True, verbose_name='Exibir Carrossel')),
                ('show_carousel_cars', models.BooleanField(default=True, verbose_name='Exibir o carro no Carrossel')),
                ('show_services', models.BooleanField(default=True, verbose_name='Exibir Seção de Serviços')),
                ('show_about_us', models.BooleanField(default=True, verbose_name="Exibir Seção 'Sobre Nós'")),
                ('show_our_numbers', models.BooleanField(default=True, verbose_name='Exibir Nossos Números')),
                ('show_book', models.BooleanField(default=True, verbose_name='Exibir Agendamento')),
                ('show_our_technicians', models.BooleanField(default=True, verbose_name='Exibir Nosso Time')),
                ('show_testimonials', models.BooleanField(default=True, verbose_name='Exibir Depoimentos')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Exibir Rodapé')),
                ('icon', models.ImageField(upload_to='carserv/images/', verbose_name='Icon da Empresa')),
                ('img_carrousel1', models.ImageField(upload_to='carserv/images/', verbose_name='Imagem 1 do Banner')),
                ('img_carrousel2', models.ImageField(upload_to='carserv/images/', verbose_name='Imagem 2 do Banner')),
                ('img_about', models.ImageField(upload_to='carserv/images/', verbose_name='Imagemda seção sobre')),
                ('img_numbers', models.ImageField(upload_to='carserv/images/', verbose_name='Imagem da seção números')),
                ('img_book', models.ImageField(upload_to='carserv/images/', verbose_name='Imagem da agendamento')),
                ('img_footer', models.ImageField(upload_to='carserv/images/', verbose_name='Imagem do rodape')),
                ('color_primary', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: #BB101F', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Primária')),
                ('color_secondary', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Secundária')),
                ('color_success', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Sucesso')),
                ('color_danger', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Perigo')),
                ('color_warning', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Aviso')),
                ('color_info', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Informação')),
                ('color_light', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Clara')),
                ('color_dark', colorfield.fields.ColorField(blank=True, default=None, help_text='Cor padrão: ', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor Escura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
