# Generated by Django 4.2.15 on 2024-09-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carserv',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço da Empresa'),
        ),
    ]
