# Generated by Django 4.2.15 on 2024-09-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carserv',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Icon da Empresa'),
        ),
        migrations.AlterField(
            model_name='carserv',
            name='img_about',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Imagemda seção sobre'),
        ),
        migrations.AlterField(
            model_name='carserv',
            name='img_book',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Imagem da agendamento'),
        ),
        migrations.AlterField(
            model_name='carserv',
            name='img_carrousel1',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Imagem 1 do Banner'),
        ),
        migrations.AlterField(
            model_name='carserv',
            name='img_carrousel2',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Imagem 2 do Banner'),
        ),
        migrations.AlterField(
            model_name='carserv',
            name='img_footer',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Imagem do rodape'),
        ),
        migrations.AlterField(
            model_name='carserv',
            name='img_numbers',
            field=models.ImageField(blank=True, null=True, upload_to='carserv/images/', verbose_name='Imagem da seção números'),
        ),
    ]
