# Generated by Django 4.2.15 on 2024-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_carserv_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
