# Generated by Django 4.2.16 on 2024-09-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carserv',
            options={'verbose_name': 'Webpage', 'verbose_name_plural': 'Webpage'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletter'},
        ),
    ]
